### ISSUE TITLE
Adding custom covariate code for deep learning 

### ISSUE THREAD

**Issue by jreps** [OHDSI/DeepPatientLevelPrediction#2]
- add custom FeatureExtraction code that doesn't involved using a join with the temporal data
- user can specify day/month/year (or any fixed interval) and it will create the corresponding data
- will test whether rowId,covariateId,all times VS rowId,covariateId,single time is more efficient 
- need to use vocabulary hierarchy

**Comment by egillax** [comment]
The lines in sql that are slow are:

**Comment by egillax** [comment]
The lines that are causing the slowness are for example from lines 32-33 in https://github.com/OHDSI/FeatureExtraction/blob/master/inst/sql/sql_server/DomainConcept.sql:


```sql
{@temporal} ? {	INNER JOIN #time_period time_period		
ON @domain_start_date <= DATEADD(DAY, time_period.end_day, cohort.cohort_start_date)		
AND @domain_end_date >= DATEADD(DAY, time_period.start_day, cohort.cohort_start_date)	
WHERE @domain_concept_id != 0
```

In my case for 200.000 patients and three years of features this took 12 hours. In my own fork of FeatureExtraction I removed those and just returned the feature start and end days. Did require me to remove the timeId from the java code and add covariate_start_day and covariate_end_day there. Then it took 34 minutes. The commit with my changes is [here](https://github.com/egillax/FeatureExtraction/commit/51953bbafd61e702714ba405e8ce47e1cd6dc9b1)

It did also require the develop branch of Andromeda since the other one doesn't support dates (see [this](https://github.com/OHDSI/Andromeda/issues/11) issue)

**Comment by ablack3** [comment]
@egillax This type of covariate would be useful for me as well (covariateId/conceptId, startDate, endDate). Can we get it added to the main FeatureExtraction branch?

**Comment by egillax** [comment]
@ablack3 this is something @jreps is currently looking at. Would be useful to hear more about your needs?

**Comment by ablack3** [comment]
I think for deep learning models it would be nice to be able to feed an entire patient history (i.e. the sequence of events prior to the index date) into a PLP model along with the time and duration of each event.

The example below gets close for drug and condition eras but does not include duration of event and might also be too slow on large data. 

``` r
library(FeatureExtraction)
library(Eunomia)

cd <- getEunomiaConnectionDetails()
createCohorts(cd)

covariateSettings <- createTemporalCovariateSettings(useDrugEraStart = TRUE,
                                                     useConditionEraStart = TRUE)

covariates <- getDbCovariateData(cd,
                                 cdmDatabaseSchema = "main",
                                 cohortId = 1,
                                 covariateSettings = covariateSettings)

#> Connecting using SQLite driver
#> Sending temp tables to server
#> Constructing features on server
#> Executing SQL took 29 secs
#> Fetching data from server
#> Fetching data took 0.152 secs

covariates$covariateRef %>% 
  select(covariateId, conceptId) %>% 
  inner_join(covariates$covariates, by = "covariateId") %>% 
  collect() %>% 
  arrange(rowId, timeId)
#> # A tibble: 1,566 x 5
#>    covariateId conceptId rowId covariateValue timeId
#>          <dbl>     <int> <int>          <int>  <int>
#>  1  4285898201   4285898     1              1    126
#>  2   260139201    260139     3              1      8
#>  3 40481087201  40481087     3              1      8
#>  4  1713332401   1713332     3              1      8
#>  5  1125315401   1125315     3              1      8
#>  6  1759842401   1759842     3              1      8
#>  7  4218389201   4218389     6              1    340
#>  8  1115008401   1115008     6              1    340
#>  9 40481087201  40481087     9              1     67
#> 10  4285898201   4285898    12              1     36
#> # ... with 1,556 more rows
```

<sup>Created on 2021-07-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jreps** [comment]
I'm going to write some code that will let a user specify the datediff part (hour, day, month, year) and the interval of interest (1, 10, 30, 100) then it will do:

timeId = floor(datediff(@part, variable_start, cohort_start)/interval)
then I can add a column duration that is datediff(@part, variable_start, min(variable_end,cohort_start ))

We just need a function that can then map this into a tensor in R and python

**Comment by jreps** [comment]
I slightly modified the code inside FE to get this: https://github.com/OHDSI/DeepPatientLevelPrediction/blob/master/inst/sql/sql_server/DomainConceptTemporal.sql 

It seems we just need minor edits to the existing SQL.  Not sure what to put as timeId and duration for non-temporal things such as gender?  Also, how to handle age?

@ablack3  - is that the sort of thing you wanted?

**Comment by egillax** [comment]
I can confirm this works and produces the same results as the original and my fork. Speed wise though this is considerably faster. I ran this on some test data, I swapped the sql files, and filled manually in the variables that need to be added in other places (like @time_part and @time_interval). In all cases I'm looking at features per day for the last year before index. It's a sample of 150 thousand patients and I'm extracting conditions, procedures and drug exposures. The original implementations does this part in 8.67 minutes, my fork gets this down to 16.3 seconds but then I still have to do the windowing in R which was from 10-30 seconds. This implementation however does it in 3.6 seconds. That's a speedup of almost x150!

Regarding age and gender, currently FE returns the timeID's as NA. I think that's fine. So I would suggest also returning NA for the duration's for those and other non-temporal variables. 

There is one variable you use, @end_day which currently at least not defined for temporalCovariateSettings.

Also maybe it would be good to be able to choose how long to look back? Something like @start_day perhaps.

**Comment by jreps** [comment]
I've added this into the standard FeatureExtraction (currently in the sequential branch but I will make a pull request into develop soon: https://github.com/OHDSI/FeatureExtraction/tree/sequential ) 

To create temporal features without the temporal table use 'createTemporalSequenceCovariateSettings':

Example: to create timeIds for every 7 days set timePart = 'day', timeInterval = 7 - here timeId 1 is up to 6 days before index, timeId 2 is 7 days to 13 days before index, etc.,

covSet <- FeatureExtraction::createTemporalSequenceCovariateSettings(useDemographicsGender = T, 
                                                           useConditionEraGroupStart = T, 
                                                           timePart = 'day', timeInterval = 7,
                                                           sequenceStartDay = -365, sequenceEndDay = -1)
 
sequenceStartDay and sequenceEndDay define when the timeIds start and end, to use a year prior to index (set sequenceStartDay = -365) up to 1 day prior to index (set sequenceEndDay = -1)

**Comment by ablack3** [comment]
It still seems like we need a way to encode the duration of a event or era in a covariate.

**Comment by ablack3** [comment]
I still seems like we don't have a way to encode the duration of an era or event in a covariate though. Two patients that have the same condition era starting on the same day but with different era lengths (e.g. 1 week vs 1 year) will end up getting the same covariate right? Of course we need to be careful not to use information after the index date.
