### ISSUE TITLE
Optimized plpData to sparse matrix

### ISSUE THREAD

**Issue by jreps** [OHDSI/DeepPatientLevelPrediction#3]
- modify current sparse matrix conversion to improve RAM usage and speed efficiency 
- maybe add a python specific sqlite to sparse matrix function

**Comment by egillax** [comment]
@jreps @chandryou @ted9219 @lhjohn 

I've added a new branch data_conversion and put the sparse matrix conversion for temporal data using RTorch in there:

https://github.com/OHDSI/DeepPatientLevelPrediction/blob/data_conversion/R/sparseRTorch.R
