### ISSUE TITLE
Transformer on develop branch not working as intended

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/DeepPatientLevelPrediction#46]
AUC is always 0.5, data conversion taking longer than on main branch.

**Comment by egillax** [comment]
The AUC issue should be fixed now in develop. Also found another issue that I fixed. Have to take a better look at the data conversion performance.

**Comment by egillax** [comment]
The issue about data conversion was due to a bug in torch, which has been fixed in the latest develop version of torch
