### ISSUE TITLE
Empty test for training-cache

### ISSUE THREAD

**Issue by egillax** [OHDSI/DeepPatientLevelPrediction#79]
Getting the following when running the tests:
```
  ══ Skipped tests (1) ═══════════════════════════════════════════════════════════
  • empty test (1): 'test-TrainingCache.R:49:1'
  ```
  
  Its [this test](https://github.com/OHDSI/DeepPatientLevelPrediction/blob/pytorch/tests/testthat/test-TrainingCache.R#L49)
  
The test is doing a runPlp where it should resume (or skip?) running hyperparameter tuning because of a previous run in same folder.  But it's missing some kind of test of the output using some `expect_*` function from `testthat`. 

Not sure if it can be detected from the output that it resumed correctly? 

Another way to test would be to manually remove the last hyperparameter combination result from the `ParameterPersistance.rds` file and then run and verify it's updated.

@lhjohn This is coming from your test, but not high priority to fix

**Comment by lhjohn** [comment]
Updated the test to do as follows:
1. Create empty cache on disk. It should return `1` as next param search index to assess.
2. Run model on this existing cache.
3. Ensure that cache now returns `NA` as next index to assess, which indicates that param search is complete.
