### ISSUE TITLE
Error when training models on full training cache

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/DeepPatientLevelPrediction#95]
The training cache allows us to resume training at the last unsolved hyperparameter combination. However, when we try to resume training from a completed cache it will return `NA` for the index to return from and throw an exception:
https://github.com/OHDSI/DeepPatientLevelPrediction/blob/2aba7580f8410d623dfb6f012ce6fed95bdf417f/R/TrainingCache-class.R#L75

Instead, in the case of a full cache this for loop in `gridCvDeep` could be skipped to directly train the final model:
https://github.com/OHDSI/DeepPatientLevelPrediction/blob/2aba7580f8410d623dfb6f012ce6fed95bdf417f/R/Estimator.R#L313

**Comment by egillax** [comment]
Fixed in develop
